name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm ci
        npm run build
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        # Artifact name
        name: tempo-extension
        # Destination path
        path: ./build
